---
title: "a ggplot2 grammar guide"
author: "Gina Reynolds"
date: "February, 2020"
output: 
  html_document:
    theme: yeti
    highlight: monochrome
---

These are my ideas about the *grammar* of ggplot2.  ggplot2 is based on the grammar of graphics.  But it has its *own* grammar too --- it is a *particular* implementation of the grammar of graphics --- and a lot of really helpful decisions are part of its grammar (like having set defaults for aesthetic scales, and scale and plot labels make it easier to build plots quickly).  If you are teaching ggplot2, you might think about teaching the grammar of ggplot2 *first* and then come back to the *grammar of graphics* --- because there will be more context for seeing how an implemenation relates to the larger philosophy.  There are a lot of great resources out there already teaching the grammar of graphics which are sources of inspiration for the *guide*.  

*Not into human language grammar?  Just ignor that first column!*

<!-- > ggplot2 is the "programmatic reflection of [the grammar of graphics] theory" - Thomas Lin Pederson -->

<!-- > mapped aesthetics are the "graphical properties of the geometries."  -->

<!-- > scales translate back and forth between values in variables and percievable properties.  -->

<!-- > "geometries are pretty much all you think about all the time" - no -->

<!-- > "basic geometries"  boxplot - rectangle and some lines... -->

<!-- > "globular..." -->

<!-- > "color profile"  in printing... -->

<!-- > theme doesn't flow from the data itself...  "aesthetically pleaseing plots are more readable and likeable, but doesn't relate to the data" -->


<!-- > "legends guides axes are instrumental to understanding the plot - how can I interpret these graphical properties" -->

<!-- Of course it's interesting to teach the grammar of graphics along with ggplot2 --- ggplot2 is an implementation of the grammar of graphics.  But ggplot2 has its own grammar, so if you are teaching that tool, might as well teach that specific grammar.  --> 

<!-- > guides... -->

<!-- > setting aesthetics, vs mapping aesthetics... -->




Grammar Analogy | How?  | What?
---|---|---
1. **The Declarative Mood**  | ggplot(data = gapminder) +| [Declaring the **data**](ggplot2_grammar_guide.html#data){target="_blank"}
2. **The Interogative Mood** |aes(**color** = pop) + | [Asking for **representation of variables by aesthetics** (color, size, x position, etc.) (also known as **aesthetic mapping**) ](ggplot2_grammar_guide.html#aes){target="_blank"}
    - *Modifiers I* | *labs(**color** = continent) +<br>labs(title = "my title") +* | [modifying *default* **aesthetic labels** (and **plot labels**)](modifiers.html#labs){target="_blank"}
    - *Modifiers II* | coord_polar() + | [modifying the *default* **coordinate system** (how the *positional* aesthetics appear - x and y)](modifiers.html#coords){target="_blank"}
    - *Modifiers III* | *scale\_**color**\_viridis_d() +* | [modifying *default* **aesthetic scales**](modifiers.html#scales){target="_blank"}
3. **Nouns** | *geom\_point() +* | [**geometric layers** taking on the aesthetics representing variables](ggplot2_grammar_guide.html#geoms){target="_blank"} 
4.**The Conditional Mood**|*geom\_point(* | [Making **local**, **geom specific** declarations rather than **global** declarations](ggplot2_grammar_guide.html#local){target="_blank"} 
| | *data = gapminder,* | **data** is <br> geom specific 
  | |  *aes(**size** = population),* |  **aesthetic representation**<br> is geom specific
||   ***color** = "blue"<br>*  | **aesthetics *not* representing variables; *unmapped* aesthetics** (i.e.  **The Imperative Mood)** 
|| ) + |
5. **Interjections**| *annotate(geom = "point", <br> x = 10, <br> y = 12, <br> color = "blue")* | [Adding context with **annotation layers**](ggplot2_grammar_guide.html#annotation){target="_blank"}
6. **Punctuation**  | *facet_wrap(~continent)*| [**faceting** breaks a plot into small plots (or *"small multiples"*) based on categorical variables ](facets_themes_ggsave.html#facets){target="_blank"}
7. **Greetings**|*theme_minimal()* | [**themes** changing plot look and feel](facets_themes_ggsave.html#themes){target="_blank"}
8. **The Written Language** | *ggsave(file = "plot.png", <br> plot = g, <br>  height = "4in", <br> width = "6in")*|[save plots with different **resolutions** and **file formats**](facets_themes_ggsave.html#saving){target="_blank"}
9. **Composition** | *library(patchwork) <br> (g1 + g2) \| g3 <br> <br> library(cowplot) <br> plotgrid(...,)* | [to be added]
10. **Concision** | last_plot(), writing functions | We've been intentionally verbose, but we can chose to be more concise
---


<!-- - *Modifiers IV* | guides() + | [to be added?] -->

### A closer look topics: geoms, themes

Above, the geom and theme topics are intentionally cursory.  There are tons of geoms, and they can get distracting.  Also themes doesn't directly relate to the data, though it is important.  Theme design almost has its own grammar, it can also be put off until fundamentals are taken on. 

1. [A closer look at geoms](geoms.html){target="_blank"}
    - [continuous - continuous](geoms.html#cc){target="_blank"}
    - [1 continuous](geoms.html#c){target="_blank"}
    - [1 discrete](geoms.html#d){target="_blank"}
    - [continuous - discrete](geoms.html#cd){target="_blank"}
    - [discrete - discrete](geoms.html#dd){target="_blank"}
2. [stats? (to be added)]
2. [A closer look at themes](taming_ggplot_themes.html){target="_blank"}
    - [Text Elements](taming_ggplot_themes.html#textelements){target="_blank"}
    - [Rectangular Elements](taming_ggplot_themes.html#rectangularelements){target="_blank"}
    - [Line Elements](taming_ggplot_themes.html#lineelements){target="_blank"}
    - [Legends](taming_ggplot_themes.html#legend){target="_blank"}
    - [Sundry](taming_ggplot_themes.html#sundry){target="_blank"}
    - [Facets](taming_ggplot_themes.html#facet){target="_blank"}
3. [A closer look at annotation]()
    - [Annotating time series](labeling_time_series.html){target="_blank"}
4. [A closer look at scales](scales.html){target="_blank"}
    


---

# Navigating the grammar guide

<a href="navigate.html" class="button">Suggested Navigation</a>

---


# More data vis topics

- spatial
- base R


# ggplot extensions

    - [ggpattern]()


```{css, echo = F}
.button {
  background-color: #4682b4; /* Blue */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
}
```




# Other guides to ggplot2

ggplot2 is very flexible, so there often there are more than one way of getting things done --- which also means there is more than one way to introduce ggplot2.
If you aren't on board with this guide (and even if you are)   you may want check out other resouces.  The more definitive and comprehensive guide to ggplot2 is, the 3rd edition of [*ggplot2: elegant graphics for data analysis*](ggplot2-book.org){target="_blank"}.  Some other workshop materials are Garrick Aden-Buie's [*A Gentle Guide to the Grammar of Graphics with ggplot2*](https://pkg.garrickadenbuie.com/gentle-ggplot2/#1){target="_blank"}, Will Chase's [*R you ready to make charts?*](https://www.williamrchase.com/slides/ggplot_intro.html#1){target="_blank"}, Malcom Barrett's [*Designing ggplots making clear figures that communicate*](https://designing-ggplots.netlify.com/#1){target="_blank"}, and Thomas Lin Pederson's [*Drawing anything with ggplot2*](https://github.com/thomasp85/ggplot2_workshop/blob/master/presentation.pdf){target="_blank"}.  [The ggplot2 cheatsheet](https://rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf){target="_blank"} is also excellent. 


# Flipbook on other topics



```{css, echo = F}
.button {
  background-color: #4682b4; /* Blue */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
}
```

<a href="https://evamaerey.github.io/data_manipulation/about" class="button">Data Wrangling</a>
<a href="https://evamaerey.github.io/statistics/about" class="button">Statistical Analysis</a>




