---
title: "gganimate"
subtitle: "a 'flipbookr' tutorial"
author: "Gina Reynolds"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 10:5
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=F}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = T, fig.retina = 3)
library(flipbookr)

```



- transition - change the data
- viewpoint - changing field of view
- shadows - memory



---

`r chunk_reveal("transitions", break_type = "rotate", widths = c(49,50))`

```{r transitions, include = F}
options(gganimate.nframes = 50)
library(tidyverse)
library(gapminder)
ggplot(data = gapminder) +
  aes(x = gdpPercap) +
  aes(y = lifeExp) +
  aes(group = country) +
  geom_point() +
  aes(color = continent) +
  aes(size = pop) +
  scale_x_log10() +
  gganimate::transition_time(time = year) + #ROTATE
  gganimate::transition_reveal(along = year) + #ROTATE
  gganimate::transition_manual(frames = continent) + #ROTATE
  NULL ->
g

animate(plot = g)
```

---

# Graphing as time series

---

`r chunk_reveal("time_series_point", break_type = "rotate", widths = c(49,50))`


```{r time_series_point, include = F}
options(gganimate.nframes = 10)
library(gapminder)
ggplot(data = gapminder) +
  aes(x = year) +
  aes(y = lifeExp) +
  aes(group = country) + 
  geom_point(size = 8) +
  aes(color = continent) +
  aes(size = pop) +
  facet_wrap(~ continent) +
  gganimate::transition_time(time = year) + #ROTATE
  gganimate::transition_reveal(along = year) + #ROTATE
  gganimate::transition_manual(frames = continent) + #ROTATE
  NULL ->
g

animate(plot = g)
```




---

# geom_line(),  geom_path

---

`r chunk_reveal("time_series", break_type = 1, widths = c(49,50))`


```{r time_series, include = F}
options(gganimate.nframes = 20)
library(gapminder)
ggplot(data = gapminder) +
  aes(x = year) +
  aes(y = lifeExp) +
  aes(group = country) + 
  geom_line() + 
  geom_point(size = 8) +
  aes(color = continent) +
  aes(size = pop) +
  facet_wrap(~ continent) +
  gganimate::transition_reveal(along = year) +
  NULL ->
g

animate(plot = g)
```


---

`r chunk_reveal("time_series_path", break_type = 1, widths = c(49,50))`


```{r time_series_path, include = F}
options(gganimate.nframes = 30)
library(gapminder)
ggplot(data = gapminder) +
  aes(x = gdpPercap) +
  aes(y = lifeExp) +
  aes(group = country) + 
  geom_path() + 
  geom_point(size = 5) +
  aes(color = continent) +
  scale_x_log10() +
  facet_wrap(~ continent) +
  gganimate::transition_reveal(along = year) + 
  NULL ->
g

animate(plot = g)
```







