---
title: "How to navigate (or teach) \"a ggplot grammar guide\""
author: "Gina Reynolds"
date: "February, 2020"
output: html_document
---


### Part I: geometric objects that take on aesthetics that represent variables from a data set (focus on aesthetic mapping - heros of data viz)

- Work through steps 1,2, & 3. A data visualization is composed of geometric shapes that taking on the aesthetics that represent variables from a data set.   Focus on *aesthetic mapping* --- this does all the heavy lifting in data visualization, so do as much aesthetic mapping as possible (use double, tripple or quadruple mapping, or exchange mappings), explore all the characteristics that we percieve that can translate from values... aes(). 

Introduce as few geoms as possible here - and only individual ones

  - point
  - tile
  - rug
  - rect
  - col
  - segment
  - text


---

- Talk about faceting "small multiples" -- where break out represents a different categorical variable (a different form of represention, kind of.)  (just do one way facet at first?)

---

- Talk *unmapped aesthetics* geom_aes(color = "blue") for the geometric objects in the plot. Across-the-board values.  Present a chart with all blue points... Is blue doing any representation for us?




---

- Talk about local data, and local aesthetics geom_point(data = , aes( ),), and layers of geoms

---

Break

---

- talk about geoms... why do we need beyond individual geoms (the diamonds example)

---

- Talk about labs() and coords() - cursory on the coords (come back to this later - the limits behavior)

---

- Talk about scales() - takes a while, lots of arguments

---



---

- Then

  - Slow down and reflect
  - Emphasize parallells between "grammar" of specifying geoms with globally defined data and aesthetics, locally defined data and aesthetics, and annotation layers
  - Demonstrate that you can mix an match local and globally specified data, aesthetics
  - Not everything needs to be specified globally or locally for a particular geom

---

### Part II: [Modifiers](modifiers.html#4){target="_blank"}

- Return to simple globally declarations plot.  Walk through modifiers I (scales_\*_?), modifiers II (labs(\* = ?)), modifiers III (coords_?).  

---

### Part III: [Facetting, Themes, Saving](facets_themes_ggsave.html){target="_blank"}

- go through 6 (this facetting topic ... also a good time to talk about patchwork and cowplot - composing a collection of plots), 7, 8


---

### Part IV: [Geoms/Stats closer look](geoms.html){target="_blank"}

geom types

  - simple
  - collective
  - after transformation

---

stats

- univariate
  - continuous
  - discrete

- bivariate
  - continuous-continuous
  - discrete-discrete
  - continuous-discrete

*long break*

### Part V: [Themes closer look](taming_themes_in_ggplot.html){target="_blank"}

themes




# More data vis topics

- spatial
- base R

```{css, echo = F}
.button {
  background-color: #4682b4; /* Blue */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
}
```


<a href="https://evamaerey.github.io/ggplot2_grammar_guide/about" class="button">Back to the grammar guide</a>


# Flipbook on other topics





<a href="https://evamaerey.github.io/data_manipulation/about" class="button">Data Wrangling</a>
<a href="https://evamaerey.github.io/statistics/about" class="button">Statistical Analysis</a>




