---
title: "ggeasy (easy theme adjustments)"
subtitle: "a flipbook | made with Xaringan"
author: "<br><br>Gina Reynolds, May 2019"
date: "<br>"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["kunoichi", "ninjutsu"]
    nature:
      ratio: "16:9"
      highlightLines: true
---

```{r setup, echo = F, eval = T, message = F, warning = F }
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.height = 6, out.width = "100%", comment = " ", cache = F, message = F, warning = F, dpi = 300)

library(flipbookr)
```




---

`r flipbookr::chunk_reveal("easy", break_type = "rotate")`

```{r easy, include = F}
library(ggeasy)
library(gapminder)
library(tidyverse)
gapminder %>%
  filter(year == 1992) %>%
  ggplot() +
  aes(x = gdpPercap, y = lifeExp) +
  geom_point(alpha = .8, shape = 21, 
             fill = "white") +
  aes(col = continent, fill = continent) +
  geom_point(alpha = .3, shape = 21) +
  aes(size = pop) +
  scale_size(guide = F) +
  labs(title = "Wealth and expected longevity\n in 1992") +
  labs(subtitle = "Data from gapminder package in R") +
  labs(x = "GDP per Capita") +
  labs(y = "Life Expectency") +
  labs(tag = "Plot 1") +
  labs(col = "Continent", fill = "Continent") +
  labs(caption = "Vis: @EvaMaeRey with ggplot") +
  easy_all_text_color(color = "green") + #ROTATE
  easy_all_text_size(size = 14) + #ROTATE
  easy_x_axis_labels_size(size = 20) + #ROTATE
  easy_legend_at(to = "bottom") + #ROTATE
  easy_adjust_legend(to = "right") + #ROTATE
  easy_plot_caption_size(size = 15) + #ROTATE
  easy_remove_y_axis() + #ROTATE
  easy_add_legend_title("hi") + #ROTATE
  easy_adjust_legend() + #ROTATE
  easy_all_text_color("#889811") + #ROTATE
  easy_all_text_colour("#889811") + #ROTATE
  easy_remove_legend() + #ROTATE
  easy_remove_legend_title() #ROTATE
```



---










```{css, eval = TRUE, echo = F}
.remark-code{line-height: 1.5; font-size: 70%}

.column-left {
  float: left;
  width: 33.333%;
}

.column-right {
  float: right;
  width: 33.333%;
}

.column-center {
  display: inline-block;
  width: 33.333%;
}
```


