---
title: "annotation in ggplot"
subtitle: "⚔<br/>made with xaringan"
author: "Gina Reynolds"
date: "2019/01/31"
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    lib_dir: libs
    css: ["kunoichi", "ninjutsu"]
    nature:
      ratio: "20:10"
      highlightLines: true
---



```{r, message = F, warning= F}

knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
knitr::opts_chunk$set(fig.height = 8, fig.width = 14,  comment = " ", cache = T)

```


```{r, warning = F, message = F}
library(countrycode)
library(tidyverse)
library(ggridges)

df <-  foreign::read.dta("raw_data/IdealpointsPublished.dta") %>% 
  mutate(`Percent agreement with US` = as.numeric(PctAgreeUS))
countries <-  df %>% 
  group_by(CountryName, ccode, CountryAbb, unsc_region) %>% 
  summarise() %>% 
  mutate(eu28 = countrycode(ccode, "cown", "eu28")) %>% 
  mutate(continent = countrycode(ccode, "cown", "continent"))
```



---

```{r, eval = T, echo = F}
df_for_graph = df %>% left_join(countries) %>% 
  filter(year %in% seq(1945, 2015, by = 5)) %>% 
  mutate(Region = ifelse(!is.na(eu28), "group 1", "group 2")) %>% 
  mutate(YearFct = fct_rev(as.factor(year))) 
  
df_for_us = df %>% 
  left_join(countries) %>%
  filter(year %in% seq(1945, 2015, by = 5) & 
           CountryAbb == "USA")

df_for_us %>% 
  ggplot() +
  aes(x = year, y = Idealpoint) +
  geom_point() ->
  g



```  



---

```{r unga_ridges, echo = F, eval = F, fig.height = 6, dpi = 300}
ggplot(df_for_graph) +
  aes(y = YearFct) +
  aes(x = Idealpoint) +
  geom_density_ridges(mapping = aes(fill = paste(YearFct, 
                                                 Region)), 
                      alpha = .8, color = "white", 
                      from = -4.5, to = 5) +
  scale_y_discrete(expand = c(0.01, 0)) +
  scale_x_continuous(expand = c(0.01, 0.2), 
                     limits = c(-5,5)) +
  scale_fill_cyclical(breaks = c("1950 group 1", "1950 group 2"), 
                      labels = c(`1950 group 1` = "Current EU Countries", 
                                 `1950 group 2` = "Non-EU Countries"), 
                      values = c("#ff0000", "#0000ff", "#ff8080", "#8080ff"), 
                      guide = "legend" ) +
  geom_point(data = df_for_us, 
             mapping = aes(y = factor(year), col = CountryAbb), 
             col = "orange", size = 3, alpha = .6, type = 21) +
  theme_ridges(grid = T) +
  theme(legend.position = c(0.76, 0.75)) +
  annotate(geom = "text", 
           x = 4.4, y = 3.7, 
           size = 4,
           label = "estimated ideal  \npoints for U.S.   ") +
  annotate(geom = "segment", x = 3.5, y = 3.9, 
           xend = 3, yend = 5,  col = "gray50") +
  annotate(geom = "segment", x = 3.5, y = 3.7, 
           xend = 2.7, yend = 4, col = "gray50") +
  annotate(geom = "segment", x = 3.5, y = 3.5, 
           xend = 3.05, yend = 3,  col = "gray50") +
  annotate(geom = "text", x = -3.25, y = 6.5, 
           label = "Cold War to\npost-Cold War\nrealignment", 
           hjust = "right") +
  annotate(geom = "segment", 
           x = -3, y = 5.5, 
           xend = -3, yend = 7.5, 
           lty = 2, lwd = .5, col = "gray34", 
           arrow = arrow(ends = "both", angle = 90, 
                         length =  unit(0.01, "npc"))) +
  labs(fill = "") +
  labs(x = "Estimated Ideal Point") +
  labs(y = "Year") +
  labs(title = "Country estimated ideal points calculation based on voting in the UN General Assembly") +
  labs(subtitle = "US vs EU (includes UK) vs other UN member") +
  labs(caption = "Visualization: Gina Reynolds (@evamaerey)\nEstimation: Voeten, Strezhnev, and Bailey, 2009") 
```


---

`r flipbookr::chunk_reveal("hello", display_type = "output")`

```{r hello, include = T, fig.height=8, fig.width=14, dpi = 300}
library(tidyverse)
dat <- read_csv("https://raw.githubusercontent.com/evoeten/United-Nations-General-Assembly-Votes-and-Ideal-Points/master/Output/IdealpointestimatesAll_Apr2020.csv") 

dat %>% 
  mutate(continent = countrycode::countrycode(ccode, 
                                              origin = "cown", 
                                              destination = "continent")) %>%  
  filter(continent == "Americas") %>% 
  mutate(Countryname = str_replace(Countryname, "of America", "")) %>% 
  mutate(Countryname = str_replace(Countryname, " and ", " & ")) %>% 
  mutate(Countryname = str_replace(Countryname, "the Grenadines", "\n the Grenadines")) %>% 
  group_by(Countryname) %>% 
  mutate(mean_ideal = mean(IdealPoint, na.rm = T)) %>% 
  ungroup() %>% 
  arrange(-mean_ideal) %>% 
  mutate(Countryname = fct_inorder(Countryname)) %>% 
  mutate(year = session + 1945) %>% 
  ggplot() +
  aes(x = year) +
  aes(y =  IdealPoint) +
  geom_line() +
  aes(group = Countryname) +
  facet_wrap(~ Countryname, scales = "free_x") +
  geom_line(data = . %>% 
              mutate(grayed = Countryname) %>% 
              select(-Countryname),
            aes(group = grayed),
            alpha = .4,
            color = "grey") +
  geom_line(color = "steelblue") +
  geom_point(data = . %>% 
               group_by(Countryname) %>%
               filter(year == max(year)),
            color = "steelblue",
            alpha = .7,
            size = 3) +
  geom_point(data = . %>% 
               group_by(Countryname) %>%
               filter(year == min(year)),
            color = "steelblue",
            alpha = .7,
            size = 4,
            shape = "|",
            fontface = "bold") +
  labs(x = NULL) +
  theme(strip.text =
          element_blank()) +
  scale_y_continuous(limits = c(-3, 4), breaks = c(-3, 0, 3)) +
  geom_text(data = . %>% 
               group_by(Countryname) %>%
               filter(year == max(year)),
            aes(label = Countryname),
            x = 1950,
            y = 4,
            size = 4,
            hjust = 0,
            vjust = 1,
            lineheight = .8,
            color = "steelblue",
            fontface = "bold") +
  scale_x_continuous(breaks = c(1950, 1970, 1990, 2010), labels = c("'50", "'70", "'90", "2010")) +
  labs(title = "Ideal point estimation based on votes at the UN General Assembly") +
  labs(y = NULL) +
  theme(plot.title.position = "plot") +
  theme(axis.ticks = element_blank()) +
  theme(axis.text.y = element_text(size = 12, margin = margin(0,-2,0,0))) +
  theme(axis.text.x = element_text(size = 12, margin = margin(-2,0,0,0))) +
  labs(subtitle = "Estimation: Michael A. Bailey, Anton Strezhnev, Erik Voeten 2015") +
  labs(caption = "Data Viz: Gina Reynolds w/ ggplot2") +
  theme(axis.line = element_blank()) +
  theme(panel.background = element_rect(fill = "#EFEDF5")) +
  theme(plot.background = element_rect(fill = "#EFEDF5")) +
  theme(text = element_text(family = "Times", color = "#090909", size = 20))
```




---

r apply_reveal("unga_ridges")`

---

